version: 2

updates:
  - package-ecosystem: conda
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /src/python
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
