name: dse-research
channels:
  - conda-forge
dependencies:
  - python=3.14
  - arviz>=0.23.4,<1.0
  - dcor
  - duckdb>=1.5.0
  - formulaic
  - graphviz
  - hatch
  - ipython>=9.11.0
  - ipywidgets>=8.1.8
  - jupytext
  - lightgbm
  - matplotlib>=3.10.8
  - mpmath
  - networkx
  - notebook>=7.5.5
  - numba>=0.64.0
  - numpy>=2.4.3
  - nutpie>=0.16.8
  - optuna
  - orjson
  - pandas-stubs
  - pandas>=3.0.1
  - pandoc
  - pingouin
  - plotly
  - polars>=1.39.2
  - preliz
  - pyarrow
  - pymc>=5.28.1,<6.0
  - pyreadstat
  - pytest>=9.0.2
  - pytorch
  - pyxlsb
  - rich
  - ruff>=0.15.5
  - scikit-learn>=1.8.0
  - scipy-stubs
  - scipy>=1.17.1
  - seaborn>=0.13.2
  - setuptools>=80.10.2
  - shap>=0.51.0
  - statsmodels
  - tabulate
  - xarray
  - xgboost
  - zarr
  - pip
  - pip:
      - jaxlib>=0.9.2
      - numpyro>=0.20.0
