# Copyright (c) 2026 Down Syndrome Education International and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

import json
import warnings
from importlib import resources

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import font_manager
from matplotlib.colors import LinearSegmentedColormap

FIGSIZE_XS = (2.913, 2.060)  # 74mm x 52mm (A8 landscape)
FIGSIZE_SM = (4.134, 2.923)  # 105mm x 74mm (A7 landscape)
FIGSIZE_MD = (5.000, 3.536)  # 127mm x 90mm
FIGSIZE_LG = (5.827, 4.120)  # 148mm x 105mm (A6 landscape)
FIGSIZE_XL = (8.268, 5.846)  # 210mm x 148.5mm (A5 landscape)
FIGSIZE_XXL = (11.693, 8.268)  # 297mm x 210mm (A4 landscape)

FIGSIZE_XS_PORTRAIT = (2.060, 2.913)  # 52mm x 74mm (A8 portrait)
FIGSIZE_SM_PORTRAIT = (2.923, 4.134)  # 74mm x 105mm (A7 portrait)
FIGSIZE_MD_PORTRAIT = (3.536, 5.000)  # 90mm x 127mm
FIGSIZE_LG_PORTRAIT = (4.120, 5.827)  # 105mm x 148mm (A6 portrait)
FIGSIZE_XL_PORTRAIT = (5.846, 8.268)  # 148.5mm x 210mm (A5 portrait)
FIGSIZE_XXL_PORTRAIT = (8.268, 11.693)  # 210mm x 297mm (A4 portrait)

DPI_NOTEBOOK = 120.0
DPI_FILE = 300.0


def _load_design_tokens() -> dict:
    """The light colours from the DSE design tokens: ``design_tokens/colors.json``, generated by
    dsegroup/apps-common and pinned in ``design_tokens/design-tokens.pin.json``. Figures are light."""
    source = resources.files("dse_research_utils.plot").joinpath("design_tokens", "colors.json")
    return json.loads(source.read_text(encoding="utf-8"))["light"]


_TOKENS = _load_design_tokens()

CHART_COLOURS: tuple[str, ...] = tuple(_TOKENS["categorical"])
"""``chart-1`` to ``chart-6``: categorical series, in order."""

TEXT_COLOUR: str = _TOKENS["foreground"]
"""Text, ticks and labels."""

MUTED_TEXT_COLOUR: str = _TOKENS["muted-foreground"]
"""Secondary text, and lines that carry meaning, such as a reference line at zero."""

LINE_COLOUR: str = _TOKENS["border"]
"""Grid lines and hairlines, which carry no meaning of their own."""

BACKGROUND_COLOUR: str = _TOKENS["background"]

SEQUENTIAL_PALETTES: dict[int, tuple[str, ...]] = {int(n): tuple(c) for n, c in _TOKENS["sequential"].items()}
"""``chart.sequential``: steps for amounts from least to most, keyed by the number of steps."""

DIVERGING_PALETTES: dict[int, tuple[str, ...]] = {int(n): tuple(c) for n, c in _TOKENS["diverging"].items()}
"""``chart.diverging``: steps either side of a midpoint, from low (orange) to high (blue), keyed by the number of
steps."""

SEQUENTIAL_CMAP = LinearSegmentedColormap.from_list("dse_sequential", _TOKENS["continuous"]["sequential"])
"""A continuous scale through the five-step sequential set, registered as ``dse_sequential``."""

DIVERGING_CMAP = LinearSegmentedColormap.from_list("dse_diverging", _TOKENS["continuous"]["diverging"])
"""A continuous scale through the five-step diverging set, registered as ``dse_diverging``."""

for _cmap in (SEQUENTIAL_CMAP, DIVERGING_CMAP, SEQUENTIAL_CMAP.reversed(), DIVERGING_CMAP.reversed()):
    if _cmap.name not in mpl.colormaps:
        mpl.colormaps.register(_cmap)

# The named hues that preceded the design tokens. Those with a categorical equivalent resolve to it; the rest keep
# their old value until callers move to a chart colour or an ordered step.
_DEPRECATED_COLOURS: dict[str, tuple[str, str]] = {
    "COLOUR_BLUE": (CHART_COLOURS[0], "CHART_COLOURS[0]"),
    "COLOUR_GREEN": (CHART_COLOURS[1], "CHART_COLOURS[1]"),
    "COLOUR_ORANGE": (CHART_COLOURS[2], "CHART_COLOURS[2]"),
    "COLOUR_PURPLE": (CHART_COLOURS[3], "CHART_COLOURS[3]"),
    "COLOUR_RED": ("#d62728", "a CHART_COLOURS entry"),
    "COLOUR_YELLOW": ("#ffbb00", "a CHART_COLOURS entry"),
    "COLOUR_DARK_BLUE": ("#014b7f", "a CHART_COLOURS entry"),
    "COLOUR_DARK_ORANGE": ("#ef7001", "a CHART_COLOURS entry"),
    "COLOUR_DARK_GREEN": ("#036903", "a CHART_COLOURS entry"),
    "COLOUR_DARK_RED": ("#910202", "a CHART_COLOURS entry"),
    "COLOUR_DARK_YELLOW": ("#ad7f01", "a CHART_COLOURS entry"),
    "COLOUR_DARK_PURPLE": ("#503a64", "a CHART_COLOURS entry"),
}


def __getattr__(name: str) -> str:
    if name in _DEPRECATED_COLOURS:
        value, replacement = _DEPRECATED_COLOURS[name]
        warnings.warn(
            f"styles.{name} is deprecated: use {replacement}, in series order, or a sequential or diverging step "
            "for ordered values.",
            DeprecationWarning,
            stacklevel=2,
        )
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


FONT_SIZE_DEFAULT = 12

FONT_FAMILY_DEFAULT = "Noto Sans"
FONT_FAMILY_MATH = "Noto Sans Math"
FONT_FAMILY_FALLBACK = "DejaVu Sans"  # ships with matplotlib, so always installed

DEFAULT_STYLE_DICT = {
    # Figure Settings
    "figure.figsize": FIGSIZE_MD,
    "figure.dpi": DPI_NOTEBOOK,
    "savefig.dpi": DPI_FILE,
    "figure.facecolor": BACKGROUND_COLOUR,
    "figure.constrained_layout.use": True,
    "figure.titlesize": FONT_SIZE_DEFAULT,
    "figure.titleweight": "bold",
    # Font and Text
    # matplotlib resolves the generic "sans-serif" to one font, the first
    # installed entry of font.sans-serif, and falls back glyph by glyph only
    # across the families listed in font.family. Noto Sans has no arrows or
    # mathematical relations (→ ≈ ≤ ✓), so DejaVu Sans draws them.
    # set_matplotlib_default_style() puts Noto Sans Math ahead of DejaVu Sans
    # when it is installed.
    "font.family": ["sans-serif", FONT_FAMILY_FALLBACK],
    "font.sans-serif": [
        FONT_FAMILY_DEFAULT,
        "Helvetica Neue LT Std",
        "Helvetica",
        "Arial",
        "DejaVu Sans",
        "sans-serif",
    ],
    # "font.stretch": "semi-condensed",
    "font.size": FONT_SIZE_DEFAULT,
    "text.color": TEXT_COLOUR,
    # Math Text
    # Noto Sans Math has a single upright face, so the italic and bold styles
    # come from Noto Sans, the text family it is designed to pair with. STIX
    # Sans supplies what Noto Sans Math cannot reach through mathtext
    # (\mathbb, sized delimiters). \mathcal renders upright.
    "mathtext.fontset": "custom",
    "mathtext.rm": FONT_FAMILY_MATH,
    "mathtext.sf": FONT_FAMILY_MATH,
    "mathtext.cal": FONT_FAMILY_MATH,
    "mathtext.it": f"{FONT_FAMILY_DEFAULT}:italic",
    "mathtext.bf": f"{FONT_FAMILY_DEFAULT}:bold",
    "mathtext.bfit": f"{FONT_FAMILY_DEFAULT}:italic:bold",
    "mathtext.fallback": "stixsans",
    # Axes
    "axes.labelsize": FONT_SIZE_DEFAULT,
    "axes.titlesize": FONT_SIZE_DEFAULT,
    "axes.titleweight": "medium",
    "axes.labelweight": "medium",
    "axes.labelcolor": TEXT_COLOUR,
    "axes.axisbelow": True,
    "axes.grid": True,
    "axes.grid.which": "major",
    "axes.facecolor": BACKGROUND_COLOUR,
    "axes.edgecolor": LINE_COLOUR,
    "axes.prop_cycle": mpl.cycler(color=CHART_COLOURS),
    "axes.linewidth": 0,
    # Grid
    "grid.linestyle": "-",
    "grid.color": LINE_COLOUR,
    "grid.linewidth": 0.25,
    "grid.alpha": 1,
    # Ticks
    "xtick.labelsize": FONT_SIZE_DEFAULT,
    "ytick.labelsize": FONT_SIZE_DEFAULT,
    "xtick.color": TEXT_COLOUR,
    "ytick.color": TEXT_COLOUR,
    "xtick.direction": "out",
    "ytick.direction": "out",
    "xtick.major.size": 0,
    "ytick.major.size": 0,
    "xtick.minor.size": 0,
    "ytick.minor.size": 0,
    # Plotting Elements (Lines, Scatters, Patches)
    "lines.solid_capstyle": "round",
    "scatter.marker": "o",
    "patch.edgecolor": BACKGROUND_COLOUR,  # drawn where forced: a gap between neighbouring segments
    "patch.linewidth": 0.75,
    "patch.antialiased": True,
    "image.cmap": SEQUENTIAL_CMAP.name,
    "pcolormesh.snap": True,
    # Legend
    "legend.fontsize": FONT_SIZE_DEFAULT,
    "legend.title_fontsize": FONT_SIZE_DEFAULT,
    "legend.frameon": True,
    "legend.numpoints": 1,
    "legend.scatterpoints": 1,
}


def set_matplotlib_default_style() -> None:
    """Applies the default custom matplotlib style dictionary.

    ``font.family`` is then set from :func:`default_font_families`, so plain text
    draws the symbols Noto Sans lacks from Noto Sans Math where it is installed.
    Like any rcParam, the setting applies to text created after the call.
    """
    plt.style.use(DEFAULT_STYLE_DICT)
    plt.rcParams["font.family"] = default_font_families()


def default_font_families() -> list[str]:
    """Return the ``font.family`` list for the default style on this machine.

    matplotlib falls back to another font glyph by glyph only across the families
    named in ``font.family``, and resolves the generic ``"sans-serif"`` to a single
    font: the first installed entry of ``font.sans-serif``. Noto Sans has no
    arrows, mathematical operators, technical symbols, geometric shapes or
    dingbats, so the list continues with Noto Sans Math, which is designed to pair
    with it, and then DejaVu Sans, which ships with matplotlib.

    Noto Sans Math is listed only when it is installed, because matplotlib logs a
    warning every time it lays out text with a named family it cannot find.

    Returns
    -------
    list[str]
        ``["sans-serif", "Noto Sans Math", "DejaVu Sans"]``, or
        ``["sans-serif", "DejaVu Sans"]`` when Noto Sans Math is not installed.
    """
    families = ["sans-serif"]
    if _font_family_installed(FONT_FAMILY_MATH):
        families.append(FONT_FAMILY_MATH)
    families.append(FONT_FAMILY_FALLBACK)
    return families


def _font_family_installed(family: str) -> bool:
    # A list, because FontProperties parses a lone string as a fontconfig pattern.
    try:
        font_manager.findfont(font_manager.FontProperties(family=[family]), fallback_to_default=False)
    except ValueError:
        return False
    return True


def categorical_palette(n: int, palette: str | None = None) -> list:
    """Return ``n`` colours for categorical series.

    By default these are the first ``n`` of :data:`CHART_COLOURS`, as hex
    strings. The DSE design language allows at most six categorical series, so a
    larger ``n`` raises ``ValueError``: group the smallest categories, split the
    figure into small multiples or label each series directly.

    A named matplotlib ``palette`` is for figures outside the design language,
    and returns RGBA tuples. Colormaps with fewer than 256 entries cycle when
    ``n`` exceeds their size, so colours can repeat. Colormaps with at least 256
    entries are sampled evenly from 0 to 1, including endpoints when ``n > 1``.
    A single colour uses 0.

    Parameters
    ----------
    n : int
        Number of series.
    palette : str, optional
        A matplotlib colormap name, in place of the chart colours.

    Returns
    -------
    list
        ``n`` colours, in series order.
    """
    if palette is None:
        if n > len(CHART_COLOURS):
            raise ValueError(
                f"{n} categorical series is more than the {len(CHART_COLOURS)} chart colours: group the smallest "
                "categories, use small multiples or label series directly, or pass a matplotlib palette"
            )
        return list(CHART_COLOURS[:n])
    cmap = plt.get_cmap(palette)
    if cmap.N >= 256:
        return [cmap(i / max(n - 1, 1)) for i in range(n)]
    return [cmap(i % cmap.N) for i in range(n)]


def sequential_palette(n: int) -> list[str]:
    """Return ``n`` ordered colours for amounts that run from least to most.

    Step 1 is the least and the lightest. Each step reaches 3:1 against
    :data:`BACKGROUND_COLOUR`, so draw neighbouring segments, such as the parts
    of a stacked bar, with ``edgecolor=BACKGROUND_COLOUR`` to keep a gap between
    them. Use :data:`SEQUENTIAL_CMAP` for a continuous scale.

    Parameters
    ----------
    n : int
        Number of ordered values, from 3 to 5.

    Returns
    -------
    list[str]
        ``n`` hex colours, least first.
    """
    return _ordered(SEQUENTIAL_PALETTES, "sequential", n)


def diverging_palette(n: int) -> list[str]:
    """Return ``n`` ordered colours for values either side of a midpoint.

    The colours run from the low or negative end, in orange, to the high or
    positive end, in blue; an odd ``n`` has a grey middle step. Survey answers
    listed from most to least positive take the colours in reverse. Each step
    reaches 3:1 against :data:`BACKGROUND_COLOUR`, so draw neighbouring
    segments with ``edgecolor=BACKGROUND_COLOUR``. Use :data:`DIVERGING_CMAP` for
    a continuous scale, such as correlations.

    Parameters
    ----------
    n : int
        Number of ordered values, from 3 to 5.

    Returns
    -------
    list[str]
        ``n`` hex colours, low end first.
    """
    return _ordered(DIVERGING_PALETTES, "diverging", n)


def _ordered(palettes: dict[int, tuple[str, ...]], kind: str, n: int) -> list[str]:
    if n not in palettes:
        sizes = ", ".join(str(k) for k in sorted(palettes))
        raise ValueError(f"no {kind} palette with {n} steps; the design tokens have {sizes}")
    return list(palettes[n])
